#!/usr/bin/python

DB_DRIVER='vertica'
DB_HOST='host01'
DB_NAME='DEV'
DB_PORT='5433'
DB_USER='akashg'
DB_PASSWORD='akashg@123'


AUDITOR_DB_DRIVER='vertica'
AUDITOR_DB_HOST='host01'
AUDITOR_DB_NAME='DEV'
AUDITOR_SCHEMA='INDUS_DEV_AUDIT'
AUDTIOR_TABLE='QUERY_AUDITOR'
AUDITOR_DB_PORT='5433'
AUDITOR_DB_USER='akashg'
AUDITOR_DB_PASSWORD='akashg@123'